# Generated by Django 5.2.8 on 2025-11-25 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Canil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição-afazeres')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluido')),
                ('prioridade', models.CharField(choices=[('1', 'Pouca performanci'), ('2', 'alta performanci'), ('3', 'performanci Essencial ')], default='1', max_length=1, verbose_name='Prioridades')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data limite')),
                ('mandado_em', models.DateTimeField(auto_now_add=True, verbose_name='mandado em')),
                ('atualizacao_task', models.DateTimeField(auto_now=True, verbose_name='tarefa Atualizada')),
                ('Trabalhos_empregados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('concluida', 'data_limite', '-prioridade', '-mandado_em'),
            },
        ),
    ]
