# Generated by Django 5.2.8 on 2025-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_canil',
            name='area',
            field=models.CharField(choices=[('IN', 'Área interna'), ('EX', 'Área externa'), ('CA', 'Área dos cachorros'), ('RE', 'Recepição')], default='IN', max_length=2, verbose_name='Área'),
        ),
    ]
